### PR TITLE
Multiple windows instances, dock menu and terminal app

### PR DESCRIPTION
**Pull request by luca-saggese**
I've added multiple instances for apps that supports it (terminal & file manager) with a dedicated context menu in dock like osx for manage them.
I've also implemented a really nice terminal app, but i need some help to fix the server side, as xterm.js only supports web socket and the current implementation of socket io with http server conflict with that

### CODE REVIEW

**Comment by jzombie** [comment]
Thanks for the update!

I'm currently wrapping up some code splitting functionality (to enable it to load selected components & modules asynchronously from the network). and will start to merge this in a few hours.

**Comment by luca-saggese** [comment]
where are you from? i’m in Italy, currently in a tuscany country house with a very bad internet connection

**Comment by jzombie** [comment]
I'm from the U.S. and have been living in Nicaragua for the past 4.5 years.

**Comment by jzombie** [comment]
I'm currently working on multi-channeled Socket.io integration over existing connection, so as not to open a new connection for each terminal window.  It should be possible.

**Pull request merged**
