### PR TITLE
more apps

### PR DESCRIPTION
**Pull request by luca-saggese**
Hi,
i've found your wonderful project while searching for a web based os for a cloud computer similar to synology/qnap.
the main features i'm lookingg for are:
- full file management,
- terminal app
- music / video jukebox
- compatibility with synology api (for viewing videos on my tv and playing music on my iphone)
- downloader app

love you system architecture and would like to share your thoughts on missing parts

regards
Luca

### CODE REVIEW

**Comment by jzombie** [comment]
Thanks for the updates!  Will have merging completed later today (it's 12:50 AM Wednesday now).

**Comment by jzombie** [comment]
That's awesome to hear!

Are you using it w/ docker-compose by any chance?

I thought about adding a searx search to it (https://github.com/asciimoo/searx) as a microservice, to serve as a backend for searching media across the web.

A demo of their utility is here:  https://searx.me/

And it supports querying via REST API.

**Comment by jzombie** [comment]
Added in preliminary web search: https://github.com/jzombie/random/blob/master/80s-music.PNG

**Comment by luca-saggese** [comment]
that’s nice!

I’m working on the file manager app, adding context menu, download / upload and folders move.

i would love also a web browser maybe with an iframe that tunnels the request trough the api, allowing me to surf the web while at work behind a proxy

**Comment by jzombie** [comment]
I've been interested in doing a proxy like that, as well.

**Comment by luca-saggese** [comment]
Found one that seems to work well is named unblocking is a web proxy, i've started integrating it the problem os more on client size scripting the iframe to get events for start load, progress and so onInviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: jzombie <notifications@github.com> Data: 11/08/19  17:48  (GMT+01:00) A: zenOSmosis/js-shell <js-shell@noreply.github.com> Cc: Luca <luca.saggese@gmail.com>, Author <author@noreply.github.com> Oggetto: Re: [zenOSmosis/js-shell] more apps (#9) I've been interested in doing a proxy like that, as well.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zenOSmosis/js-shell/pull/9?email_source=notifications\u0026email_token=ACP5KKPOKMDWOA34BN6IN2DQEAYEJA5CNFSM4IJ2RH52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4BDMRY#issuecomment-520238663",
"url": "https://github.com/zenOSmosis/js-shell/pull/9?email_source=notifications\u0026email_token=ACP5KKPOKMDWOA34BN6IN2DQEAYEJA5CNFSM4IJ2RH52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4BDMRY#issuecomment-520238663",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jzombie** [comment]
Is there a link for it?

**Pull request merged**
